Milestone 4
imran5644/react-calculator-app pull request #3
Opened 2021-05-17 15:47 UTC by imran5644

Add the logic folder with methods:
1) Calculate method
2) Operate method
3) Import calculate on App component
4) Import operate on calculate

2021-05-17 17:38 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @imran5644**

Great job with the project so far. calculate.js is imported in the app.js file, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] in the calculate function, make sure to include every case such as when you click on a number, when you click on the '=' button, when you click on any of the other operators.
- [ ] in the operate function, make sure to include a case for the '%' button.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-05-17 18:55 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @imran5644, great job on this project :fireworks: The "calculate" function and the "operate" function have been addressed :+1: However, I have realized that in the "operate" function we are missing an important requirement that needs to be addressed before proceeding.

- Kindly take a closed look at this requirement
`operate` switches `operation` and uses `plus`, `minus`, `times`, `div` and `modifier` (turning the number into a percentage based number, `e.g. 95 % == .95`) functions. So instead of using our normal mathematical operation sign as currently, let us rather use the methods above

Once this is resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-17 19:49 UTC, imran5644 commented
@addod19 I am done with the changes. so please approve my project.

2021-05-17 20:15 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @imran5644, Awesome job sor far!!! We are almost there. Kindly make a little adjustment to the `operate.js` file in line `32` as in the comment below:
Make use of the `mod()` method as mentioned in the previous review

Once this is done, we are good to go :rocket: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-05-17 20:15 UTC, addod19 commented on src/logic/operate.js
> +      return { total: bigFirstNum, next: bigSecondNum.div(100), operation };
Kindly use `mod` here instead of the `div(100)`. This is all left to approve the project :smile:

2021-05-18 07:43 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

- [ ] OPTIONAL - This should be required but has been added as an optional change. You were right the first time I apologize for the mixup in the previous review. Please consider changing the `.mod` back to `.div(100)` because the `%` is a percentage operator, not a modifier operator.

Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-18 14:47 UTC, merged